from .const import DETECTION_CONF_TEST, DETECTION_IOU_TEST, DETECTION_CONF_PROD, DETECTION_IOU_PROD, \
    INVISION_DETECTION_MODEL_CURRENT_VERSION, INVISION_DETECTION_MODEL

from .utils import print_device_info
from ..utils.log import get_logger

logger = get_logger(__name__)


def load_detection_model_test(version: str = INVISION_DETECTION_MODEL_CURRENT_VERSION):
    """
    Loads the detection model for TESTING purposes.
    - Lower confidence threshold to catch more detections
    - No GPU enforced, runs on CPU fine
    - Useful for quick sanity checks and debugging

    Args:
        version: Model version to load (e.g. "v1.0.0"). Defaults to current version.

    Returns:
        model: YOLOv5 model instance ready for inference
    """
    import torch 
    from ultralytics import YOLO

    
    model_info = INVISION_DETECTION_MODEL[version]
    weights    = str(model_info["filename"])
    device     = "cuda" if torch.cuda.is_available() else "cpu"

    logger.info(f"🧪 Loading Detection Model {version} in TEST mode ({model_info['architecture']} | {model_info['train_run']})...")
    print_device_info(device)

    model                   = YOLO(weights)
    model.overrides["conf"] = DETECTION_CONF_TEST
    model.overrides["iou"]  = DETECTION_IOU_TEST
    model.to(device)

    logger.info(f"✅ Test model loaded from '{weights}' on {device.upper()}")
    return model


def load_detection_model_prod(version: str = INVISION_DETECTION_MODEL_CURRENT_VERSION):
    """
    Loads the detection model for PRODUCTION purposes.
    - GPU (CUDA) : loads .pt directly — fastest on your RX 5500 XT
    - CPU        : exports to TFLite float32 for better CPU performance (e.g. Raspberry Pi)

    TFLite export structure generated by ultralytics:
        weights/
        └── invision_detection_v1_saved_model/
            ├── invision_detection_v1_float32.tflite  ← we use this by default
            ├── invision_detection_v1_float16.tflite
            └── saved_model.pb
    """
    import torch
    import numpy as np
    from ultralytics import YOLO
    from pathlib import Path

    model_info   = INVISION_DETECTION_MODEL[version]
    weights_path = Path(model_info["filename"])  # e.g. weights/invision_detection_v1.pt
    device       = "cuda" if torch.cuda.is_available() else "cpu"

    logger.info(f"🚀 Loading Detection Model {version} in PROD mode...")

    if device == "cpu":
        # ── TFLite paths ──────────────────────────────────────────
        saved_model_dir = weights_path.parent / f"{weights_path.stem}_saved_model"
        tflite_float32  = saved_model_dir / f"{weights_path.stem}_float32.tflite"

        # ── Export if not already done ────────────────────────────
        if not saved_model_dir.exists() or not tflite_float32.exists():
            logger.info(f"⚙️  CPU detected — exporting to TFLite...")
            temp_model = YOLO(str(weights_path))
            temp_model.export(format="tflite", int8=False)
            del temp_model  # ← free memory immediately after export
            logger.info(f"✅ Export complete!")
        else:
            logger.info(f"✅ TFLite export already exists at '{saved_model_dir}'")

        if not tflite_float32.exists():
            raise FileNotFoundError(f"float32 TFLite not found at '{tflite_float32}'.")

        # ── Load TFLite ───────────────────────────────────────────
        logger.info(f"📦 Loading float32 TFLite from '{tflite_float32}'...")
        tflite_model = YOLO(str(tflite_float32), task="detect")

        # ── Wrap and return early ─────────────────────────────────
        def predict(source, **kwargs):
            return tflite_model.predict(
                source  = source,
                conf    = DETECTION_CONF_PROD,
                iou     = DETECTION_IOU_PROD,
                verbose = kwargs.get("verbose", False),
            )

        logger.info(f"✅ Prod model loaded on CPU (TFLite float32)")
        return predict  # ← early return, skip GPU code entirely

    # ── GPU path — only reached if device != cpu ──────────────────
    logger.info(f"📦 Loading .pt weights from '{weights_path}'...")
    model = YOLO(str(weights_path))
    model.overrides["conf"] = DETECTION_CONF_PROD
    model.overrides["iou"]  = DETECTION_IOU_PROD
    model.to(device)

    # ── Warmup ────────────────────────────────────────────────────
    logger.info("🔥 Warming up model...")
    model(np.zeros((640, 640, 3), dtype=np.uint8), verbose=False)
    logger.info(f"✅ Prod model loaded on {device.upper()}")

    return model



if __name__ == "__main__":
    model = load_detection_model_prod()

    

